import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  llmSidebar: [{type: 'autogenerated', dirName: 'llm'}],
  llamacppSidebar: [{type: 'autogenerated', dirName: 'llama-cpp'}],
  sglangSidebar: [{type: 'autogenerated', dirName: 'sglang'}],
  vllmSidebar: [{type: 'autogenerated', dirName: 'vllm'}],
};

export default sidebars;
