import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mlBasicsSidebar: [{type: 'autogenerated', dirName: 'ml-basics'}],
  llmSidebar: [{type: 'autogenerated', dirName: 'llm'}],
  promptSidebar: [{type: 'autogenerated', dirName: 'prompt-engineering'}],
  aiAppSidebar: [{type: 'autogenerated', dirName: 'ai-application'}],
};

export default sidebars;
